#!/bin/sh /etc/rc.common
# chinadns init script

START=90

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
	service_start /usr/bin/chinadns \
		-s 114.114.114.114,8.8.4.4 \
		-l /etc/chinadns_iplist.txt \
		-c /etc/chinadns_chnroute.txt \
		-p 5353
	iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5353
}

stop() {
	iptables -t nat -D PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5353
	service_stop /usr/bin/chinadns
}
